# Generated by Django 3.1.4 on 2020-12-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
    ]
